import psycopg2
import collections


class DBManager:
    def __init__(self, cfg: dict):
        try:
            self.connection = psycopg2.connect(**cfg)
        except (psycopg2.DatabaseError, Exception) as error:
            print(error)

    def __del__(self):
        self.connection.close()

    def create_table(self, table_name: str, columns: list):

        query = (f"CREATE TABLE {table_name} ("
                 f"id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "
                 f"" + ", ".join(map(lambda col:f"{col['name']} {col['type']}", columns)) +
                 f")")
        print(query)
        cur = self.connection.cursor()
        try:
            cur.execute(query)
        except Exception as err:
            self.connection.rollback()
            print('\033[91m'+ "ERROR: " + str(err) + '\033[0m')

        self.connection.commit()
        cur.close()

    def add_data_to_table(self, table_name: str, json_data: list):
        if len(json_data) == 0:
            return

        query = f"INSERT INTO {table_name} ({", ".join(collections.OrderedDict(sorted(json_data[0].items())).keys())}) VALUES "
        for i in range(0, len(json_data)):
            od = collections.OrderedDict(sorted(json_data[i].items()))
            vals = map(lambda x: str(x) if isinstance(x, (int, float)) else f"'{str(x)}'", od.values())
            query += f"({", ".join(vals)}), "
            query = query.replace("'None'", 'NULL')
        query = query.rstrip(", ")
        query += ";"
        print(query)
        cur = self.connection.cursor()
        cur.execute(query)
        self.connection.commit()
        cur.close()